package View;

import Controller.ControllerImp;
import Model.CD;
import java.io.File;
import java.util.ArrayList;
import javax.swing.Action;
import javax.swing.JFileChooser;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author duyba
 */
public class GUI extends javax.swing.JFrame implements View {

    /**
     * Creates new form GUI
     */
    private DefaultTableModel model;
    private Action action;
    static private String CDID ="";

    public GUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.model = (DefaultTableModel) Tble.getModel();
        action = new ControllerImp(this);
        actionPerform();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackG = new javax.swing.JPanel();
        LeftSide = new javax.swing.JPanel();
        LeftSideP1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BAdd = new javax.swing.JButton();
        BRemove = new javax.swing.JButton();
        BUpdate = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textSearch = new javax.swing.JTextField();
        SearchIcon = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tble = new javax.swing.JTable();
        jlCount = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuFile = new javax.swing.JMenu();
        MenuOpen = new javax.swing.JMenuItem();
        MenuSave = new javax.swing.JMenuItem();
        MenuExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        BackG.setBackground(new java.awt.Color(255, 255, 255));
        BackG.setName(""); // NOI18N
        BackG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LeftSide.setBackground(new java.awt.Color(54, 44, 89));
        LeftSide.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LeftSideP1.setBackground(new java.awt.Color(85, 65, 118));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Funitions");
        LeftSideP1.add(jLabel2);

        LeftSide.add(LeftSideP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 300, 60));

        BAdd.setBackground(new java.awt.Color(255, 255, 255));
        BAdd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/plus-5-32.png"))); // NOI18N
        BAdd.setText("ADD CD");
        BAdd.setFocusable(false);
        LeftSide.add(BAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 190, 80));

        BRemove.setBackground(new java.awt.Color(255, 255, 255));
        BRemove.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete-48.png"))); // NOI18N
        BRemove.setText("REMOVE");
        BRemove.setFocusable(false);
        LeftSide.add(BRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 190, 80));

        BUpdate.setBackground(new java.awt.Color(255, 255, 255));
        BUpdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/edit-2-48.png"))); // NOI18N
        BUpdate.setText("UPDATE CD");
        BUpdate.setFocusable(false);
        LeftSide.add(BUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 190, 80));

        BackG.add(LeftSide, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 860));

        jPanel1.setBackground(new java.awt.Color(110, 89, 222));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CD HOUSE PROGRAM");

        textSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textSearchKeyReleased(evt);
            }
        });

        SearchIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/search-3-32.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(jLabel1)
                .addContainerGap(488, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SearchIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(217, 217, 217))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SearchIcon)
                    .addComponent(textSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        BackG.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 25, 1090, -1));

        Tble.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Collection", "ID", "Type", "Title", "Price", "Year"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tble.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tble);

        BackG.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 870, 350));

        jlCount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlCount.setText("Count");
        BackG.add(jlCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 644, 110, 20));

        MenuFile.setText("File");

        MenuOpen.setText("Open");
        MenuFile.add(MenuOpen);

        MenuSave.setText("Save");
        MenuFile.add(MenuSave);

        MenuExit.setText("Exit");
        MenuFile.add(MenuExit);

        jMenuBar1.add(MenuFile);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackG, javax.swing.GroupLayout.PREFERRED_SIZE, 1215, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackG, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TbleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbleMouseClicked
        setCount();
        loadDataFromTable();
    }//GEN-LAST:event_TbleMouseClicked

    private void textSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textSearchKeyReleased
        String titile = textSearch.getText().toUpperCase();
        printSearch(titile);
    }//GEN-LAST:event_textSearchKeyReleased

    public String getCDByTable() {
        return CDID;
    }

    public void printSearch(String titile) {
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(model);
        Tble.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(titile));
    }

    public void setCount() {
        int row = Tble.getSelectedRow();
        jlCount.setText("" + "Count: " + (row + 1) + "/" + Tble.getRowCount());
    }

    public void loadDataFromTable() {
        int rows = Tble.getSelectedRow();
        CDID = Tble.getValueAt(rows, 1).toString();

    }

    public String File() {
        JFileChooser Jfile = new JFileChooser();
        Jfile.setCurrentDirectory(new File("."));
        int respone = Jfile.showOpenDialog(null);
        if (respone == 0) {
            File file = new File(Jfile.getSelectedFile().getAbsolutePath());
            String path = String.valueOf(file);
            return path;
        }
        return "";
    }

    public String SaveFile() {
        JFileChooser Jfile = new JFileChooser();
        Jfile.setCurrentDirectory(new File("."));
        int respone = Jfile.showSaveDialog(null);
        if (respone == 0) {
            File file = new File(Jfile.getSelectedFile().getAbsolutePath());
            String path = String.valueOf(file);
            return path;
        }
        return "";
    }

    public void printListCD(ArrayList<CD> list) {
        this.showData(list, model);
    }

    private void actionPerform() {
        this.BAdd.addActionListener(action);
        this.BRemove.addActionListener(action);
        this.BUpdate.addActionListener(action);
        this.MenuOpen.addActionListener(action);
        this.MenuSave.addActionListener(action);
        this.MenuExit.addActionListener(action);
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAdd;
    private javax.swing.JButton BRemove;
    private javax.swing.JButton BUpdate;
    private javax.swing.JPanel BackG;
    private javax.swing.JPanel LeftSide;
    private javax.swing.JPanel LeftSideP1;
    private javax.swing.JMenuItem MenuExit;
    private javax.swing.JMenu MenuFile;
    private javax.swing.JMenuItem MenuOpen;
    private javax.swing.JMenuItem MenuSave;
    private javax.swing.JLabel SearchIcon;
    private javax.swing.JTable Tble;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlCount;
    private javax.swing.JTextField textSearch;
    // End of variables declaration//GEN-END:variables

    @Override
    public <T> void showData(ArrayList<T> list, DefaultTableModel model) {
        model.setRowCount(0);
        for (T t : list) {
            CD cd = (CD) t;
            Object[] rowData = new Object[7];
            rowData[0] = cd.getName().toUpperCase();
            rowData[1] = cd.getId();
            String type = "Video";
            if (cd.isType()) {
                type = "Audio";
            }
            rowData[2] = type;
            rowData[3] = cd.getTitle().toUpperCase();
            rowData[4] = cd.getPrice();
            rowData[5] = cd.getYear();
            this.model.addRow(rowData);
        }
    }
}
