/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.CD;
import javax.swing.Action;
import javax.swing.JOptionPane;

/**
 *
 * @author duyba
 */
public class UPDATE extends javax.swing.JFrame {

    /**
     * Creates new form UPDATE
     */
    public UPDATE() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jBback = new javax.swing.JButton();
        ConfrimUpdate = new javax.swing.JButton();
        JBoxName = new javax.swing.JComboBox<>();
        jLcollection = new javax.swing.JLabel();
        jLType = new javax.swing.JLabel();
        jLID = new javax.swing.JLabel();
        jLTitle = new javax.swing.JLabel();
        jLprices = new javax.swing.JLabel();
        jLcollection5 = new javax.swing.JLabel();
        TxtTitle = new javax.swing.JTextField();
        TxtPrice = new javax.swing.JTextField();
        Txtyear = new javax.swing.JTextField();
        rAudio = new javax.swing.JRadioButton();
        rVideo = new javax.swing.JRadioButton();
        IDconstaint = new javax.swing.JLabel();

        setUndecorated(true);

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("UPDATING");

        jBback.setBackground(new java.awt.Color(204, 255, 255));
        jBback.setText("<<<<Back");
        jBback.setFocusable(false);
        jBback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(104, 104, 104)
                .addComponent(jBback))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jBback)
                        .addGap(0, 47, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)))
                .addContainerGap())
        );

        ConfrimUpdate.setBackground(new java.awt.Color(204, 255, 255));
        ConfrimUpdate.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        ConfrimUpdate.setText("UPDATE");
        ConfrimUpdate.setFocusable(false);

        JBoxName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JBoxName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Game", "Movie", "Music" }));
        JBoxName.setFocusable(false);

        jLcollection.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLcollection.setText("Collection");

        jLType.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLType.setText("Type");

        jLID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLID.setText("ID");

        jLTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLTitle.setText("Title");

        jLprices.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLprices.setText("Unit Prices");

        jLcollection5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLcollection5.setText("Pub Year");

        buttonGroup1.add(rAudio);
        rAudio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rAudio.setText("Audio");

        buttonGroup1.add(rVideo);
        rVideo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rVideo.setText("Video");

        IDconstaint.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 139, Short.MAX_VALUE)
                        .addComponent(ConfrimUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(189, 189, 189))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLType, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(rAudio, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TxtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLcollection, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JBoxName, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLprices, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLcollection5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Txtyear, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLID, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(IDconstaint, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 194, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IDconstaint, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLID))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLcollection)
                    .addComponent(JBoxName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLType)
                    .addComponent(rAudio)
                    .addComponent(rVideo))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTitle)
                    .addComponent(TxtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLprices)
                    .addComponent(TxtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLcollection5)
                    .addComponent(Txtyear, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addComponent(ConfrimUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbackActionPerformed
        resetForm();
        this.setVisible(false);
    }//GEN-LAST:event_jBbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public void action(Action action) {
        this.ConfrimUpdate.addActionListener(action);
    }

    public boolean checkEmpty() {
        if (TxtTitle.getText().isEmpty()
                || TxtPrice.getText().isEmpty()
                || Txtyear.getText().isEmpty()) {
            return false;
        }
        return true;
    }
    
     public void resetForm() {
        this.IDconstaint.setText("");
        this.Txtyear.setText("");
        this.TxtTitle.setText("");
        this.TxtPrice.setText("");
        this.rAudio.setSelected(true);
        this.JBoxName.setSelectedIndex(0);
    }

    public void getCDChooseen(CD cd) {
        IDconstaint.setText(cd.getId() + "");
        TxtTitle.setText(cd.getTitle() + "");
        TxtPrice.setText(String.valueOf(cd.getPrice()) + "");
        Txtyear.setText(String.valueOf(cd.getYear()) + "");
        if (cd.isType()) {
            rAudio.setSelected(true);
        }
        if (cd.isType() == false) {
            rVideo.setSelected(true);
        }
        if (cd.getName().equalsIgnoreCase("game")) {
            JBoxName.setSelectedIndex(0);
        }
        if (cd.getName().equalsIgnoreCase("Movie")) {
            JBoxName.setSelectedIndex(1);
        }
        if (cd.getName().equalsIgnoreCase("music")) {
           JBoxName.setSelectedIndex(2);
        }
    }
    
      public CD createNewCD() {
        boolean check = true;
        String name = JBoxName.getSelectedItem().toString();
        String id = IDconstaint.getText();
        String title = TxtTitle.getText();
        boolean type = false;
        double price = 0.0;
        int year = 0;
        if(rAudio.isSelected()){
            type = true;
        }
        if (title.matches("\\W+")) {
            JOptionPane.showMessageDialog(null, "Titile cannot have special character!!!");
            check = false;
        }
        try {
            price = Double.parseDouble(TxtPrice.getText());
            if(price<0){
                JOptionPane.showMessageDialog(null, "Price greater than 0");
                check = false;
            }
        } catch (Exception e) {
            check = false;
            JOptionPane.showMessageDialog(null, "Price is a number!!!");
        }
        try {
            year = Integer.parseInt(Txtyear.getText());
            if(year > 2022 || year <1500){
                JOptionPane.showMessageDialog(null, "Year is invalid!!!");
                check = false;
            }
        } catch (Exception e) {
            check = false;
            JOptionPane.showMessageDialog(null, "Year is a number!!!");
        }

        if (check) {
            CD cd = new CD(name, id, type, title, price, year);
            return cd;
        }

        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConfrimUpdate;
    private javax.swing.JLabel IDconstaint;
    private javax.swing.JComboBox<String> JBoxName;
    private javax.swing.JTextField TxtPrice;
    private javax.swing.JTextField TxtTitle;
    private javax.swing.JTextField Txtyear;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBback;
    private javax.swing.JLabel jLID;
    private javax.swing.JLabel jLTitle;
    private javax.swing.JLabel jLType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLcollection;
    private javax.swing.JLabel jLcollection5;
    private javax.swing.JLabel jLprices;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rAudio;
    private javax.swing.JRadioButton rVideo;
    // End of variables declaration//GEN-END:variables
}
